/*
 * File: catMenus.ui.js
 * Date: Sun Jun 24 2012 21:26:41 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

catMenusUi = Ext.extend(Ext.TabPanel, {
    activeTab: 0,
    width: 435,
    height: 293,
    forceLayout: true,
    initComponent: function() {
        this.items = [
            {
                xtype: 'grid',
                title: 'Listado',
                store: 'stoCmsMenus',
                ref: 'gridMenus',
                tbar: {
                    xtype: 'toolbar',
                    items: [
                        {
                            xtype: 'button',
                            text: 'Nuevo'
                        },
                        {
                            xtype: 'button',
                            text: 'Editar'
                        },
                        {
                            xtype: 'buttongroup',
                            columns: 2,
                            items: [
                                {
                                    xtype: 'button',
                                    text: 'Activar',
                                    enableToggle: true,
                                    pressed: true
                                },
                                {
                                    xtype: 'button',
                                    text: 'Desactivar',
                                    enableToggle: true
                                }
                            ]
                        },
                        {
                            xtype: 'button',
                            text: 'Eliminar'
                        }
                    ]
                },
                bbar: {
                    xtype: 'paging',
                    store: 'stoCmsMenus'
                },
                columns: [
                    {
                        xtype: 'gridcolumn',
                        header: 'id',
                        dataIndex: 'id',
                        sortable: true,
                        width: 100
                    },
                    {
                        xtype: 'gridcolumn',
                        header: 'texto',
                        dataIndex: 'texto',
                        sortable: true,
                        width: 100
                    },
                    {
                        xtype: 'gridcolumn',
                        header: 'target',
                        dataIndex: 'target',
                        sortable: true,
                        width: 100
                    }
                ]
            },
            {
                xtype: 'form',
                title: 'Edicion',
                forceLayout: true,
                ref: 'frmMenu',
                tbar: {
                    xtype: 'toolbar',
                    items: [
                        {
                            xtype: 'button',
                            text: 'Nuevo',
                            ref: '../../btnNuevo'
                        },
                        {
                            xtype: 'button',
                            text: 'Guardar',
                            ref: '../../btnGuardar'
                        },
                        {
                            xtype: 'buttongroup',
                            columns: 2,
                            items: [
                                {
                                    xtype: 'button',
                                    text: 'Activar',
                                    enableToggle: true,
                                    pressed: true
                                },
                                {
                                    xtype: 'button',
                                    text: 'Desactivar',
                                    enableToggle: true
                                }
                            ]
                        },
                        {
                            xtype: 'button',
                            text: 'Eliminar'
                        }
                    ]
                },
                items: [
                    {
                        xtype: 'textfield',
                        fieldLabel: 'id',
                        anchor: '100%',
                        name: 'id'
                    },
                    {
                        xtype: 'textfield',
                        fieldLabel: 'Texto',
                        anchor: '100%',
                        name: 'texto'
                    },
                    {
                        xtype: 'textfield',
                        fieldLabel: 'Target',
                        anchor: '100%',
                        name: 'target'
                    }
                ]
            }
        ];
        catMenusUi.superclass.initComponent.call(this);
    }
});
