/*
 * File: stoCmsMenus.js
 * Date: Sun Jun 24 2012 21:26:41 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

stoCmsMenus = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        stoCmsMenus.superclass.constructor.call(this, Ext.apply({
            storeId: 'stoCmsMenus',
            url: 'menus/getList',
            root: 'data',
            messageProperty: 'msg',
            fields: [
                {
                    name: 'id'
                },
                {
                    name: 'texto'
                },
                {
                    name: 'target'
                }
            ]
        }, cfg));
    }
});
new stoCmsMenus();