/*
 * File: xds_index.js
 * Date: Sun Jun 24 2012 21:26:42 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.onReady(function() {
    Ext.QuickTips.init();
    var cmp1 = new catMenus({
        renderTo: 'div_cat_menus'
    });
    cmp1.show();
});
