/*
 * File: gridMonitoreoHorarios.ui.js
 * Date: Wed May 30 2012 21:17:01 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

gridMonitoreoHorariosUi = Ext.extend(Ext.grid.GridPanel, {
    width: 282,
    height: 290,
    autoExpandColumn: 'colEstado',
    frame: true,
    initComponent: function() {
        this.columns = [
            {
                xtype: 'gridcolumn',
                header: 'Hora Inicio',
                dataIndex: 'horaInicio',
                sortable: true,
                width: 75
            },
            {
                xtype: 'gridcolumn',
                header: 'Hora Fin',
                dataIndex: 'horaFin',
                sortable: true,
                width: 66
            },
            {
                xtype: 'gridcolumn',
                header: 'Estado',
                sortable: true,
                width: 80,
                dataIndex: 'estado',
                id: 'colEstado'
            }
        ];
        this.bbar = {
            xtype: 'paging',
            displayInfo: true,
            displayMsg: '{0} - {1} de {2}',
            emptyMsg: 'No data',
            pageSize: 7,
            afterPageText: ' '
        };
        gridMonitoreoHorariosUi.superclass.initComponent.call(this);
    }
});
