/*
 * File: gridMonitoreoHorarios.js
 * Date: Sat May 19 2012 20:31:33 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

gridMonitoreoHorarios = Ext.extend(gridMonitoreoHorariosUi, {
    initComponent: function() {
        gridMonitoreoHorarios.superclass.initComponent.call(this);
		this.store= new stoMonitoreoHorarios();
		this.bottomToolbar.bind(this.store);
    }
});
Ext.reg('gridHorarios',gridMonitoreoHorarios);