/*
 * File: gridMonitoreoDispositivos.ui.js
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

gridMonitoreoDispositivosUi = Ext.extend(Ext.grid.GridPanel, {
    width: 297,
    height: 290,
    autoExpandColumn: 'colNombre',
    frame: true,
    initComponent: function() {
        this.columns = [
            {
                xtype: 'gridcolumn',
                header: 'Nombre',
                dataIndex: 'nombre',
                sortable: true,
                width: 150,
                id: 'colNombre'
            },
            {
                xtype: 'gridcolumn',
                header: 'Tipo',
                dataIndex: 'tipo',
                sortable: true,
                width: 100,
                hidden: true,
                id: 'colTipo'
            },
            {
                xtype: 'gridcolumn',
                header: 'Estado',
                dataIndex: 'estado',
                sortable: true,
                width: 80
            }
        ];
        this.bbar = {
            xtype: 'paging',
            displayInfo: true,
            displayMsg: '{0} - {1} de {2}',
            pageSize: 9,
            emptyMsg: 'No data'
        };
        gridMonitoreoDispositivosUi.superclass.initComponent.call(this);
    }
});
