/*
 * File: stoMonitoreoDispositivos.js
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

stoMonitoreoDispositivos = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        stoMonitoreoDispositivos.superclass.constructor.call(this, Ext.apply({
            root: 'data',
            url: 'monitoreo/getDispositivos',
            messageProperty: 'msg',
            idProperty: 'idDispositivo',
            fields: [
                {
                    name: 'idDispositivo'
                },
                {
                    name: 'nombre'
                },
                {
                    name: 'tipo'
                },
                {
                    name: 'imagen'
                },
                {
                    name: 'estado'
                },
                {
                    name: 'fecha'
                }
            ]
        }, cfg));
    }
});
Ext.reg('stoMonitoreoDispositivos', stoMonitoreoDispositivos);