/*
 * File: frmUsuario.js
 * Date: Sun Jun 03 2012 22:03:32 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

frmUsuario = Ext.extend(frmUsuarioUi, {
    initComponent: function() {
        frmUsuario.superclass.initComponent.call(this);
    }
});
