/*
 * File: stoHorarios.js
 * Date: Sun Jun 03 2012 22:16:06 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

stoHorarios = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        stoHorarios.superclass.constructor.call(this, Ext.apply({
            storeId: 'stoHorarios',
            root: 'data',
            url: 'programacion/getHorarios',
            messageProperty: 'msg',
            fields: [
                {
                    name: 'id'
                },
                {
                    name: 'horaInicio',
                    type: 'string'
                },
                {
                    name: 'horaFin'
                },
                {
                    name: 'cancelado'
                },
                {
                    name: 'dispositivoId'
                },
                {
                    name: 'dia'
                }
            ]
        }, cfg));
    }
});
new stoHorarios();