/*
 * File: frmUsuario.ui.js
 * Date: Sun Jun 03 2012 22:03:38 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

frmUsuarioUi = Ext.extend(Ext.form.FormPanel, {
    title: 'Usuario',
    width: 400,
    height: 267,
    padding: 10,
    style: '',
    bodyStyle: 'padding:8px;',
    initComponent: function() {
        this.items = [
            {
                xtype: 'textfield',
                fieldLabel: 'Nombre',
                anchor: '100%'
            },
            {
                xtype: 'textfield',
                fieldLabel: 'Email',
                anchor: '100%'
            },
            {
                xtype: 'fieldset',
                title: 'Contraseña',
                items: [
                    {
                        xtype: 'checkbox',
                        fieldLabel: 'Autogenerar',
                        anchor: '100%'
                    },
                    {
                        xtype: 'textfield',
                        fieldLabel: 'Contraseña',
                        anchor: '100%'
                    },
                    {
                        xtype: 'textfield',
                        fieldLabel: 'Confirmación',
                        anchor: '100%'
                    }
                ]
            },
            {
                xtype: 'button',
                text: 'Guardar',
                style: 'float:right;margin-right:2px;'
            }
        ];
        this.tbar = {
            xtype: 'toolbar',
            items: [
                {
                    xtype: 'button',
                    text: 'Nuevo'
                },
                {
                    xtype: 'button',
                    text: 'Guardar'
                },
                {
                    xtype: 'button',
                    text: 'Eliminar'
                },
                {
                    xtype: 'button',
                    text: 'Deshacer'
                }
            ]
        };
        frmUsuarioUi.superclass.initComponent.call(this);
    }
});
