/*
 * File: frmAdminHorarios.ui.js
 * Date: Sun Jun 03 2012 22:16:06 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

frmAdminHorariosUi = Ext.extend(Ext.Panel, {
    unstyled: true,
    style: '',
    bodyStyle: 'padding:8px;',
    layout: 'form',
    initComponent: function() {
        this.items = [
            {
                xtype: 'displayfield',
                value: '<div class="titulo">Programación Semanal</div>',
                anchor: '100%',
                hideLabel: true,
                style: 'text-align:center;',
                ref: 'dspTitulo'
            },
            {
                xtype: 'container',
                width: 290,
                items: [
                    {
                        xtype: 'fieldset',
                        title: 'Seleccione ',
                        layout: 'hbox',
                        labelAlign: 'top',
                        width: 595,
                        items: [
                            {
                                xtype: 'container',
                                layout: 'form',
                                labelAlign: 'top',
                                width: 333,
                                items: [
                                    {
                                        xtype: 'combo',
                                        fieldLabel: 'Dia de la semana',
                                        width: 120,
                                        store: 'stoDias',
                                        mode: 'local',
                                        itemId: 'cmbDias',
                                        displayField: 'nombre',
                                        valueField: 'id',
                                        triggerAction: 'all',
                                        hiddenValue: '',
                                        ref: '../../../cmbDias'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                layout: 'form',
                                labelAlign: 'top',
                                items: [
                                    {
                                        xtype: 'combo',
                                        width: 210,
                                        fieldLabel: 'Dispositivo',
                                        store: 'stoDispositivos',
                                        mode: 'local',
                                        triggerAction: 'all',
                                        displayField: 'nombre',
                                        valueField: 'id',
                                        ref: '../../../cmbDispositivos',
                                        id: 'cmbDispositivos'
                                    }
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'grid',
                title: 'Horarios del dia',
                store: 'stoHorarios',
                width: 282,
                height: 404,
                autoExpandColumn: 'colEstado',
                frame: true,
                style: 'float:left;margin-right:60px;',
                boxMaxWidth: 282,
                ref: 'gridHorarios',
                columns: [
                    {
                        xtype: 'gridcolumn',
                        header: 'Hora Inicio',
                        dataIndex: 'horaInicio',
                        sortable: true,
                        width: 75
                    },
                    {
                        xtype: 'gridcolumn',
                        header: 'Hora Fin',
                        dataIndex: 'horaFin',
                        sortable: true,
                        width: 66
                    },
                    {
                        xtype: 'gridcolumn',
                        header: 'Cancelado',
                        sortable: true,
                        width: 80,
                        dataIndex: 'cancelado',
                        id: 'colEstado'
                    }
                ],
                bbar: {
                    xtype: 'paging',
                    displayInfo: true,
                    displayMsg: '{0} - {1} de {2}',
                    emptyMsg: 'No data',
                    pageSize: 12,
                    afterPageText: ' '
                }
            },
            {
                xtype: 'form',
                title: 'Edicion de Horario',
                style: 'float:left;',
                width: 254,
                height: 403,
                bodyStyle: 'padding:8px;',
                ref: 'frmEdicion',
                tbar: {
                    xtype: 'toolbar',
                    items: [
                        {
                            xtype: 'button',
                            text: 'Nuevo',
                            icon: 'http://saw/imagenes/add1.png',
                            ref: '../../btnNuevo'
                        },
                        {
                            xtype: 'button',
                            text: 'Guardar',
                            icon: 'http://saw/imagenes/save_16.png',
                            disabled: true,
                            ref: '../../btnGuardar'
                        },
                        {
                            xtype: 'button',
                            text: 'Borrar',
                            disabled: true,
                            icon: 'http://saw/imagenes/list_remove.png',
                            ref: '../../btnEliminar'
                        }
                    ]
                },
                items: [
                    {
                        xtype: 'fieldset',
                        items: [
                            {
                                xtype: 'timefield',
                                fieldLabel: 'Fecha Inicio',
                                width: 100,
                                name: 'horaInicio'
                            },
                            {
                                xtype: 'timefield',
                                fieldLabel: 'Fecha Fin',
                                width: 100,
                                name: 'horaFin'
                            }
                        ]
                    },
                    {
                        xtype: 'checkbox',
                        fieldLabel: 'Cancelado',
                        anchor: '100%',
                        name: 'cancelado',
                        value: 'asd'
                    },
                    {
                        xtype: 'fieldset',
                        items: [
                            {
                                xtype: 'displayfield',
                                value: 'Seleccione un elemento de la lista de horarios para editarlo',
                                fieldLabel: 'Label',
                                anchor: '100%',
                                hideLabel: true
                            }
                        ]
                    },
                    {
                        xtype: 'textfield',
                        fieldLabel: 'id',
                        anchor: '100%',
                        name: 'id',
                        readOnly: true,
                        hidden: true,
                        hideLabel: true,
                        ref: '../txtId'
                    },
                    {
                        xtype: 'textfield',
                        fieldLabel: 'dispositivoId',
                        anchor: '100%',
                        name: 'dispositivoId',
                        readOnly: true,
                        hidden: true,
                        hideLabel: true,
                        ref: '../txtIdDispositivo'
                    },
                    {
                        xtype: 'textfield',
                        fieldLabel: 'dia',
                        anchor: '100%',
                        name: 'dia',
                        readOnly: true,
                        hidden: true,
                        hideLabel: true,
                        ref: '../txtDia'
                    },
                    {
                        xtype: 'button',
                        text: 'Guardar',
                        icon: 'http://saw/imagenes/save_16.png',
                        style: 'float:right;margin-right:1px;',
                        ref: '../btnGuardar2'
                    }
                ]
            }
        ];
        frmAdminHorariosUi.superclass.initComponent.call(this);
    }
});
